# /**
# * Setting of containers for developing html web pages.
# *
# * @author Nick
# * @date 04/07/2024
# * @detail Please use compose to execute the yaml file
# */
version: "3.8"

services:
  javamaven:
    build: ./javaMaven
    container_name: javaMaven
    working_dir: /programs
    restart: unless-stopped
    volumes:
      - "./workspace:/programs"
    networks:
      - dev
    command: tail -f /dev/null

networks:
  dev: